
FROM python:3.11-slim
WORKDIR /app
RUN apt update && apt install -y curl && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
#CMD ["python", "par_impar/main.py"]


#CMD ["python", "process_redis.py"]
ENTRYPOINT ["python", "-u", "process_redis.py"]